### ISSUE TITLE
ReferenceError: Cannot access 'params' before initialization

### ISSUE THREAD

**Issue by grz-gajda** [livechat/accounts-sdk#14]
Package version: `2.0.7`

---

In my authorization flow exists something like this:

```ts
accountsSDK.redirect().authorizeData()
  .then(/* do something */)
  .catch(() => {
    accountsSDK.redirect().authorize()
  })
```

Unfortunately I've got an error

```
sdk.js:121 Uncaught (in promise) ReferenceError: Cannot access 'params' before initialization
    at AccountsSDK.authorizeURL (sdk.js:121:5)
    at Redirect.authorize (redirect.js:17:26)
```

because line in [sdk.js#121](https://github.com/livechat/accounts-sdk/blob/baaa2dd4c43f7fcecd5033fb03a1826fe6a76f8c/src/sdk.js#L121) uses a variable from line [sdk.js#129](https://github.com/livechat/accounts-sdk/blob/baaa2dd4c43f7fcecd5033fb03a1826fe6a76f8c/src/sdk.js#L129).

**Comment by wojciechdudek-text** [comment]
Hi, for now you can switch back to v2.0.6. Tomorrow we will release v2.0.8 that fixes this bug.

**Comment by wojciechdudek-text** [comment]
v2.0.8 has been released. Let me know if it fixes your problem. Sorry for inconvenience.

**Comment by wojciechdudek-text** [comment]
I assume that issue can be closed now.
